# Esta configuração será injetada dentro do bloco http padrão do Nginx
server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Otimizações para não sobrecarregar a RAM/CPU do host
    client_body_buffer_size 10K;
    client_header_buffer_size 1k;
    client_max_body_size 8m;
    large_client_header_buffers 2 1k;

    # 1. Servir o Frontend Estático
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy Seletivo para o Backend (Apenas API e Auth)
    # proxy_buffering off garante que o vídeo não fique preso na RAM do frontend
    location /System {
        proxy_pass ${JELLYFIN_SERVER};
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_buffering off;
        proxy_request_buffering off;
    }

    location /Users {
        proxy_pass ${JELLYFIN_SERVER};
        proxy_buffering off;
    }

    location /Sessions {
        proxy_pass ${JELLYFIN_SERVER};
        proxy_buffering off;
    }
}
